version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      frontend-security:
        applies-to: security-updates
        update-types:
          - patch
          - minor
  - package-ecosystem: npm
    directory: /solana/layerzero
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      solana-lz-security:
        applies-to: security-updates
        update-types:
          - patch
          - minor
  - package-ecosystem: npm
    directory: /solana-layerzero
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      solana-bridge-security:
        applies-to: security-updates
        update-types:
          - patch
          - minor
