name: Update Documentation

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'contracts/**'
      - 'docs/**'
      - 'README.md'

  workflow_dispatch: # Allow manual trigger

jobs:
  update-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for changelog generation
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Compile Contracts
        run: npm run compile
      
      - name: Generate Contract Documentation
        run: |
          node scripts/generate-contract-docs.js
      
      - name: Generate Update Log
        id: generate_log
        run: |
          node scripts/generate-update-log.js
          echo "timestamp=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
      
      - name: Prepare Documentation Package
        run: |
          mkdir -p docs-export/team/Updates/Smart-Contracts
          
          # Copy main documentation
          cp -r docs/* docs-export/team/Updates/Smart-Contracts/
          
          # Copy generated files
          cp -r docs-generated/* docs-export/team/Updates/Smart-Contracts/ || true
          
          # Create index file
          node scripts/create-docs-index.js
      
      # Option 1: Push to separate docs repository
      - name: Push to Docs Repository (Option 1)
        if: secrets.DOCS_DEPLOY_TOKEN != ''
        env:
          DOCS_REPO_URL: ${{ secrets.DOCS_REPO_URL }}
          DOCS_DEPLOY_TOKEN: ${{ secrets.DOCS_DEPLOY_TOKEN }}
        run: |
          git clone https://${DOCS_DEPLOY_TOKEN}@github.com/47-Eagle/docs.git docs-repo
          
          # Copy to correct location
          mkdir -p docs-repo/team/Updates/Smart-Contracts
          cp -r docs-export/team/Updates/Smart-Contracts/* docs-repo/team/Updates/Smart-Contracts/
          
          cd docs-repo
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "ðŸ¤– Auto-update: Smart Contract docs (${{ steps.generate_log.outputs.timestamp }})" || exit 0
          git push
      
      - name: Create Deployment Summary
        run: |
          echo "## ðŸ“ Documentation Updated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Timestamp:** ${{ steps.generate_log.outputs.timestamp }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Location:** https://docs.47eagle.com/team/Updates/Smart-Contracts" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Files Updated:" >> $GITHUB_STEP_SUMMARY
          ls -1 docs-export/team/Updates/Smart-Contracts/ >> $GITHUB_STEP_SUMMARY
      
      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-${{ github.sha }}
          path: docs-export/
          retention-days: 30
